pipeline {
    agent any // Or a specific Docker agent if you have one configured

    environment {
        // IMPORTANT: Configure these as 'Secret text' credentials in Jenkins
        // and replace 'BROWSERSTACK_USERNAME_ID' and 'BROWSERSTACK_ACCESS_KEY_ID'
        // with the actual IDs of your Jenkins credentials.
        BROWSERSTACK_USERNAME = credentials('BROWSERSTACK_USERNAME_ID')
        BROWSERSTACK_ACCESS_KEY = credentials('BROWSERSTACK_ACCESS_KEY_ID')
    }

    stages {

        stage('Install Dependencies') {
            steps {
                sh 'npm install'
            }
        }

        stage('Run BrowserStack Tests') {
            steps {
                browserstack(credentialsId: 'b0bed252-9ced-435a-b4ee-68b948ef9860') {
                    sh 'npx wdio test.conf.js'
                 }  
                
            }
        }
    }

    post {
        always {
            // This block runs regardless of the build result.
            // You can add steps here for cleanup, archiving artifacts, etc.

            // Example: Archive the screenshot generated by the test
            archiveArtifacts artifacts: 'app_screenshot.png', fingerprint: true
        }
    }
}