pipeline {
    agent {
        docker {
            image 'node:lts'
            args '-u 0' // Run as root inside the container to avoid permission issues
        }
    }

    environment {
        // IMPORTANT: Configure these as 'Secret text' credentials in Jenkins
        // and replace 'BROWSERSTACK_USERNAME_ID' and 'BROWSERSTACK_ACCESS_KEY_ID'
        // with the actual IDs of your Jenkins credentials.
        BROWSERSTACK_USERNAME = 'mehdibouallagui1'
        BROWSERSTACK_ACCESS_KEY = 'ks1QMgftzqmNqaC2jNzM'
    }

    stages {
        stage('Checkout') {
            when { branch 'main' }
            steps {
                git 'https://github.com/mbouallagui/mbouallagui.github.io.git'
            }
        }

        stage('Run BrowserStack Tests') {
            steps {
                sh 'npm install'
                sh 'npx wdio test.conf.js'
            }
        }
    }

    post {
        always {
            // This block runs regardless of the build result.
            // You can add steps here for cleanup, archiving artifacts, etc.

            // Example: Archive the screenshot generated by the test
            archiveArtifacts artifacts: 'app_screenshot.png', fingerprint: true
        }
    }
}